[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install && cd server && npm install"]

[phases.build]
cmds = ["npx expo export --platform web"]

[start]
cmd = "cd server && node index.js"
